env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: warn

settings:
  react:
    version: 17.0.2