FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package.json /app/
COPY yarn.lock /app/
RUN yarn
COPY ./ /app/
# ENV REACT_APP_BACKEND_URL='http://backend:5000'
# ENV REACT_APP_CHAT_URL='http://chat:9001'
RUN yarn build

FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build-stage /app/build/ /etc/nginx/html/