version: '3'

services:
  proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - frontend
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - frontend
    ports:
      - '80:80'
    depends_on:
      - backend
      - chat
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./compose.env
    networks:
      - frontend
    expose:
      - '5000'
  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    networks:
      - frontend
    env_file:
      - ./compose.env
    expose:
      - '5000'
    environment:
      - PORT=5000
networks:
  frontend: