version: '3'

services:
  proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - frontend
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - frontend
    expose:
      - '80'
    depends_on:
      - backend
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./compose.env
    networks:
      - backend
      - frontend
    expose:
      - '5000'
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    expose:
      - '27017'
    networks:
      - backend
    volumes:
      - data:/data/db
networks:
  frontend:
  backend:
volumes:
  data: