version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:5000'
    env_file: ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'